# Configuration for Release Drafter - https://github.com/toolmantim/release-drafter

name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: ':boom: Breaking Change'
    label: 'Type: Breaking Change'

  - title: ':rocket: Enhancement'
    label: 'Type: Enhancement'

  - title: ':bug: Bug Fix'
    label: 'Type: Bug'

  - title: ':nail_care: Refactor'
    label: 'Type: Refactor'

  - title: ':memo: Documentation'
    label: 'Type: Documentation'

  - title: ':house: Internal'
    label: 'Type: Internal'

  - title: ':wrench: Tooling'
    label: 'Type: Tooling'

  - title: ':package: Dependencies'
    label: 'Type: Dependencies'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
template: |
  $CHANGES
  ***

  ### Contributors

  $CONTRIBUTORS

  ***

  For full changes, see the [comparison between $PREVIOUS_TAG and v$NEXT_PATCH_VERSION](https://github.com/nrfta/go-mgql/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION)
